apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: 535002893779.dkr.ecr.us-east-1.amazonaws.com/riabanerjee/portfolio/client:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production