# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: portfolio
  region: us-east-1
  version: "1.31"

iam:
  withOIDC: true  # enables IRSA — pods can assume IAM roles

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true   # nodes go in private subnets
    amiFamily: AmazonLinux2
    labels:
      role: worker
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/portfolio: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true        # Cluster Autoscaler permissions
        albIngress: true        # AWS Load Balancer Controller permissions
        cloudWatch: true        # Container Insights permissions
        ebs: true               # EBS CSI driver permissions

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator