apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: default
data:
  RESTRICT_IP: "{{ .Values.server.config.restrictIP }}"
  PORT: "{{ .Values.server.config.port }}"
  MAIL_SERVER: "{{ .Values.server.config.mailServer }}"
  MAIL_PORT: "{{ .Values.server.config.mailPort }}"
  MAIL_USE_TLS: "{{ .Values.server.config.mailUseTLS }}"
  MAIL_USE_SSL: "{{ .Values.server.config.mailUseSSL }}"
  GOOGLE_RECAPTCHA_URL: "{{ .Values.server.config.recaptchaURL }}"