apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: default
type: Opaque
data:
  EMAIL_PASSWORD: {{ .Values.server.secrets.emailPassword | b64enc | quote }}
  RECAPTCHA_SECRET_KEY: {{ .Values.server.secrets.recaptchaSecretKey | b64enc | quote }}
  ALLOWED_IP: {{ .Values.server.secrets.allowedIP | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.server.secrets.openaiAPIKey | b64enc | quote }}