aws:
  accountId: "535002893779"
  region: us-east-1
  ecrRegistry: 535002893779.dkr.ecr.us-east-1.amazonaws.com

client:
  image:
    repository: 535002893779.dkr.ecr.us-east-1.amazonaws.com/riabanerjee/portfolio/client
    tag: latest
  replicas: 2
  port: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  hpa:
    maxReplicas: 6
    targetCPU: 70

server:
  image:
    repository: 535002893779.dkr.ecr.us-east-1.amazonaws.com/riabanerjee/portfolio/server
    tag: latest
  replicas: 2
  port: 5002
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  hpa:
    maxReplicas: 6
    targetCPU: 70
  config:
    restrictIP: "false"
    port: "5002"
    mailServer: "smtp.gmail.com"
    mailPort: "587"
    mailUseTLS: "True"
    mailUseSSL: "False"
    recaptchaURL: "https://www.google.com/recaptcha/api/siteverify"
  secrets:
    emailPassword: ""
    recaptchaSecretKey: ""
    allowedIP: ""
    openaiAPIKey: ""

ingress:
  scheme: internet-facing
  targetType: ip